config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'dakokus/index'
  get 'sessions/new'
  get 'users/new'
  get 'homes/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'homes#index'
  resources :users
  resources :dakokus
  resources :schedules


    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

end

app/models/a.rb
class A < ApplicationRecord
belongs_to :user,optional: true 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :as
  has_many :bs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end



end

app/controllers/dakokus_controller.rb
class DakokusController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def index
  @a=current_user.as.all
  end

def new
  @a = A.new
  @a.d_id=params[:d_id]
end

  def create
    #binding.pry
    @a = current_user.as.new(schedule_params)
    if @a.save
      redirect_to  schedules_path, success: '登録が完了しました'
    else
       flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

def edit
@a=current_user.as.find_by(d_id: params[:id])
#@a=current_user.as.find(params[:d_id])
end

def update
 @a=current_user.as.find_by(d_id: params[:id])
 #@a=current_user.as.find(params[:d_id])
 @a.update(schedule_params)
 redirect_to schedules_path
end

  private
   def schedule_params
     params.require(:a).permit(:d_id,:selection,:start_time,:end_time,:break,:description)
   end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
require "pry"
  def new
    end
    def create

      user = User.find_by(email: session_params[:email])
      if user && user.authenticate(session_params[:password])
        log_in user
        redirect_to dakokus_index_path, success: 'ログインに成功しました'
        current_user
        #binding.pry
      else
        flash.now[:danger] = 'ログインに失敗しました'
        render :new
      end
    end

    def destroy
      log_out
      redirect_to root_url, info: 'ログアウトしました'
    end

    def log_out
        #binding.pry
      session.delete(:user_id)
      @current_user = nil
    end

    private
    def log_in(user)
      session[:user_id] = user.id
    end

    private
    def session_params
      params.require(:session).permit(:email,:password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
require "pry"
  def new
    @user = User.new
  end

  def create
    #binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'

    else
       flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private
   def user_params
     params.require(:user).permit(:name, :email,:password, :password_confirmation)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end


end

app/helpers/bs_helper.rb
module BsHelper
end

app/helpers/cs_helper.rb
module CsHelper
end

app/helpers/dakokus_helper.rb
module DakokusHelper
end

app/helpers/ds_helper.rb
module DsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dakokus/index.html.erb
<html lang="ja">
  <head>
    <title>timer</title>
    <style>
      td.clock_cell {
        text-align: center;
        width: 100%;
        height: 135px;
        font-family: YuGothic;
        font-size: 70pt;
      }
      #id_colon {
        padding: 0 10px;
      }
    </style>
    <script>
      onload = function () {
        myTimeprev()
        setInterval(myTimeprev, 1000);
      }

      function set2figures(num) {
        var ret;
        if (num < 10) {
          ret = "0" + num;
        } else {
          ret = num;
        }
        return ret;
      }

      function myTimeprev() {
        var Nowymdhms = new Date();
        var NowYear = Nowymdhms.getFullYear();
        var NowMon = Nowymdhms.getMonth() + 1;
        var NowDay = Nowymdhms.getDate();
        var NowWeek = Nowymdhms.getDay();
        var NowHour = Nowymdhms.getHours();
        var NowMin = set2figures(Nowymdhms.getMinutes());
        var NowSec = set2figures(Nowymdhms.getSeconds());
        var Week = new Array("日", "月", "火", "水", "木", "金", "土");
        var myMsg1 = NowYear + "年" + NowMon + "月" + NowDay + "日(" + Week[NowWeek] + ")";
        var myMsg2 = NowHour;
        var myMsg3 = NowMin;
        var myMsg4 = NowSec;
        document.getElementById('id_now_date').innerText = myMsg1;
        document.getElementById('id_now_hour').innerText = myMsg2;
        document.getElementById('id_now_minute').innerText = myMsg3;
        document.getElementById('id_now_second').innerText = myMsg4;
      }
    </script>

    <script type="text/javascript">
    $(function(){
        setInterval(function(){
            $("#id_colon1").fadeOut(500,function(){$(this).fadeIn(500)});
        },1000);
    });
    </script>
    <script type="text/javascript">
    $(function(){
        setInterval(function(){
            $("#id_colon2").fadeOut(500,function(){$(this).fadeIn(500)});
        },1000);
    });
    </script>
  </head>

  <body>
    <div style="	position: relative;top: 50%;left: 50%;transform: translate(-50%, -55%);width:80%;position:absolute;margin: auto;background-color: #fff;border-radius: 8px; border:#5CC632 1px solid;border-width: medium">
      <table style="width:100%;margin-top: 10px;">
        <tbody>
          <tr>
            <td id="id_dakoku_cell" style=" height:500px; display:block;">
              <table style="width:100%;height:400px;position: absolute;top: 50%;left: 50%;transform: translate(-50%, -50%)">
                <tbody>
                  <tr>
                    <td style="padding-left:180px; padding-right:17px; width:500px;">

                      <table>
                        <tbody>
                          <tr>
                            <td style="padding-bottom:20px;">

                              <table style="width:500px; border-radius:0.5em; border:#999 1px solid;border-width: thin">
                                <tbody>
                                  <tr>
                                    <td style="text-align:center; border:0px solid #000000;">

                                      <table style="width:100%; background-color:#ffffff; border-radius: 0.5em 0.5em 0px 0px / 0.5em 0.5em 0px 0px;">
                                        <tbody>
                                          <tr>
                                            <td id="id_now_date" style=" text-align:center; font-size:20pt; padding-top:15px;"></td>
                                          </tr>

                                          <tr>
                                            <td class="clock_cell" style="background-color: rgb(255, 255, 255);">
                                              <span id="id_now_hour"></span><span id="id_colon1" style="visibility: visible;">:</span>
                                              <span id="id_now_minute"></span><span id="id_colon2" style="visibility: visible;">:</span>
                                              <span id="id_now_second"></span>
                                            </td>
                                          </tr>

                                          <tr>
                                            <td id="id_selected_kubun" style="text-align:center; font-size:22pt; padding-bottom:21px;">退勤</td>
                                          </tr>
                                        </tbody>
                                      </table>
                                    </td>
                                  </tr>
                                </tbody>
                              </table>

                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                    <td style="padding-bottom:21px;padding-left:80px;padding-top:46px">
                      <table>
                        <tbody>
                          <tr>
                            <td>
                              <table>
                                <tbody>
                                  <tr>
                                    <td>

                                      <fieldset class="login_data_field">

                                        <table>
                                          <tbody>
                                            <tr>
                                              <td>

                                                <table>
                                                  <tbody>
                                                    <tr>
                                                      <tr>
                                                        <td class="login_data_title_cell"style="text-align:center;">
                                                          氏名
                                                        </td>
                                                        <td class="login_data_cell" style="position:relative; right:-5px;">
                                                            <%=current_user.name %>
                                                          </td>


                                                      </tr>
                                                      <tr>
                                                        <td colspan="2" style="color:#ffffff; text-align:center; padding:5px 10px 8px 13px;">
                                                          <span style="color:#5f7cae;">
                                                            <b>打刻ボタンを押してください</b>
                                                          </span>
                                                        </td>
                                                      </tr>
                                                    </tbody>
                                                  </table>

                                                </td>
                                              </tr>
                                              <tr>
                                                <td style="text-align:center; padding-top:10px;">
                                                  <input type="button" name="dakoku" value="打　　　　刻" class="btn btn-large dakoku_button" style="background: rgb(235, 235, 235); border: none; ">
                                                </td>
                                              </tr>
                                            </tbody>
                                          </table>

                                        </fieldset>

                                      </td>
                                    </tr>
                                  </tbody>
                                </table>

                              </td>
                            </tr>
                            <tr>
                              <td style="padding-top:0px; text-align:center;">

                                <fieldset class="main_button_field">
                                  <table>
                                    <tbody>
                                      <tr style="height:43px;">
                                        <td>
                                          <input type="hidden" name="main_button">
                                        </td>
                                        <td>
                                          <input type="hidden" name="main_button">
                                        </td>
                                      </tr>
                                      <tr style="height:43px;">
                                        <td>
                                          <input type="button" name="main_button" value="出　勤" class="btn btn-default btn-lg active" id="btn-default1" >
                                        </td>
                                        <td style="padding-left: 50px;">
                                          <input type="button" name="main_button" value="退　勤" class="btn btn-default btn-lg active" id="btn-default2">
                                        </td>
                                      </tr>
                                      <tr style="height:43px;">
                                        <td>
                                          <input type="hidden" name="main_button">
                                        </td>
                                        <td>
                                          <input type="hidden" name="main_button">
                                        </td>
                                      </tr>
                                      <tr style="height:43px;">
                                        <td>
                                          <input type="hidden" name="main_button">
                                        </td>
                                        <td>
                                          <input type="hidden" name="main_button">
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </fieldset>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

    </body>
    <script type="text/javascript">
      $('#btn-default2').on('click',function() {
          document.getElementById("id_selected_kubun").innerHTML = "退勤";
           //alert("クリックされました");
        });
          </script>

          <script type="text/javascript">

        $('#btn-default1').on('click',function() {
          document.getElementById("id_selected_kubun").innerHTML = "出勤";
          //alert("クリックされました");
        });
    </script>

  </html>

app/views/homes/index.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>


  </head>
  <body>


<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', sessions_new_path,class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kintai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container ">
        <span class="logo-img">
        <%= link_to root_path do %>
        <%= image_tag "icons/logo2.png"%>
      <% end %>
      </span>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to '/admin/login' do %>
            <%= image_tag "icons/kanri.png" %>
          <% end %>
        </li>
      <li>
        <%= link_to dakokus_path do %>
        <%= image_tag "icons/clock.png" %>
      <% end %>
    </li>
    <li>
      <%= link_to schedules_path do %>
      <%= image_tag "icons/calendar.png" %>
      <% end %>
  </li>
  <li>
    <%= link_to logout_path, method: :delete do %>
    <%= image_tag "icons/logout.png" %>
  <% end %>
</li>
<% else %>
  <li><%= link_to '/admin/login' do %>
    <%= image_tag "icons/kanri.png" %>
  <% end %>
</li>
<li>
  <%= link_to users_new_path do %>
  <%= image_tag "icons/register.png" %>
<% end %>
</li>
<li><%= link_to sessions_new_path do %>
<%= image_tag "icons/login.png" %>
<% end %></li>
<% end %>
</ul>
</div>
</nav>
<%= yield %>
<script>

$(function () {
$(".alert").fadeOut(5000);
});
</script>
</body>
</html>

app/views/schedules/edit.html.erb
<html>
<head>
<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=SHIFT_JIS">
<title>Sample</title>
</head>
<body>
  <%d= Date.today %>
    <% c= ["日","月","火","水","木","金","土"]%>

  <div class="users-new-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-4 col-md-4 users-new-container">
          <h1 class="text-center text-white"><%=d.strftime("%Y年%m月%d日")%></h1>
          <%=form_for @a ,url:schedule_path do |f| %>
            <div class="form-group">
              <%= f.label :selection, "勤務区分", class: "text-white" %>
<%= f.select :selection, [["-"],["出勤"], ["有給"], ["休み"]],{}, {class: 'form-control'}%>
            </div>
            <div class="form-group ">
              <%= f.label "開始：時間", class: "text-white " %>
              <%= f.time_field :start_time,class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label "終了：時間", class: "text-white" %>
              <%= f.time_field :end_time,class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label "休憩：時間", class: "text-white" %>
              <%= f.time_field :break,class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label "作業日報", class: "text-white" %>
              <%= f.text_area :description,class: "form-control" %>
            </div>

            <%= f.submit "登録する", class: "btn-block btn-white" %>
          <% end %>
           <%= link_to '勤務一覧へ', schedules_path,class: 'text-white' %>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/schedules/new.html.erb
<html>
<head>
<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=SHIFT_JIS">
<title>Sample</title>
</head>
<body>
  <%d= Date.today %>
    <% c= ["日","月","火","水","木","金","土"]%>

  <div class="users-new-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-4 col-md-4 users-new-container">
          <h1 class="text-center text-white"><%=d.strftime("%Y年%m月%d日")%></h1>
          <%= form_for @a ,url: schedules_path do |f| %>
            <div class="form-group">
              <%= f.label :selection, "勤務区分", class: "text-white" %>
<%= f.select :selection, [["-"],["出勤"], ["有給"], ["休み"]],{}, {class: 'form-control'}%>
            </div>
            <div class="form-group ">
              <%= f.label "開始：時間", class: "text-white " %>
              <%= f.time_field :start_time,class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label "終了：時間", class: "text-white" %>
              <%= f.time_field :end_time,class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label "休憩：時間", class: "text-white" %>
              <%= f.time_field :break,class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label "作業日報", class: "text-white" %>
              <%= f.text_area :description,class: "form-control" %>
            </div>

            <%= f.submit "登録する", class: "btn-block btn-white" %>
          <% end %>
           <%= link_to '勤務一覧へ', schedules_path,class: 'text-white' %>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
                      <%= f.label :password, class: 'text-white' %>
                      <%= f.password_field :password, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= f.label :password_confirmation, class: 'text-white' %>
                      <%= f.password_field :password_confirmation, class: 'form-control' %>
                    </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', sessions_new_path,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>